services:
  frontend-react:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
